"""added description column to repository

Revision ID: 439ae7039b6a
Revises: f309077ef53a
Create Date: 2026-04-21 18:41:09.734893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439ae7039b6a'
down_revision = 'f309077ef53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
